### ISSUE TITLE
Create user profile model

### ISSUE THREAD

**Issue by JasonTHChen** [LMYC/Lmyc-website#1]
Add User model:
- User Name
- Password
- Ability to change password
- First Name
- Last Name
- Member status
    - Full member good standing (can book a boat)
    - Full member not good standing
    - Associate member
    - Social member
    - Admin
    - Booking Moderator
- Skipper status
    - Crew
    - Day skipper
    - Cruise skipper
- Address
- Phone number
    - Mobile
    - Home
    - Work
- Emergency contact info * 2
- Sailing qualifications
- Skills
- Sailing experience

System should display credits allocated at beginning of season, and credits used for each reservation,
and balance of credits available for future bookings

**Comment by Castielketaimo** [comment]
User Model is created, This issues have been resolved.
