### ISSUE TITLE
Docker CLI command doesnt work

### ISSUE THREAD

**Issue by JasonTHChen** [LMYC/Lmyc-website#18]
To Run under CLI, please go to root of the project and run
`docker-compose -f docker-compose.yml up`

![image](https://user-images.githubusercontent.com/20535909/37391651-0cbe6ef0-2729-11e8-9cd2-7c2211d00ccc.png)

**Comment by Castielketaimo** [comment]
Tested on my machine, works fine. The issue could be just due to your local database history etc
