### ISSUE TITLE
Create Volunteer model

### ISSUE THREAD

**Issue by Castielketaimo** [LMYC/Lmyc-website#33]
- Date
- Duration (number of hours)
- Description
- Classification Code:
  - Boat Maint (Hard)
  - Boat Maint (Monthly)
  - Training
  - Cruise Skipper (Training)
  - Day Skipper
  - Executive
  - Winter Watch
  - etc

**Comment by siyang7** [comment]
Can't find this table in the requirements; not sure what its purpose is or what the fields following "etc" would be. Where is this table from and where can we find more details regarding its purpose in requirements doc?

Thanks
